#Prerequise create RDS Oracle and ElastiCache Redis Cluster


# Ubuntu 20.04

#Install Oracle Client

#Source : https://gist.github.com/rutcreate/778ade900fa144bf9a16aa405082fb45

mkdir -p /opt/oracle
cd /opt/oracle
wget https://download.oracle.com/otn_software/linux/instantclient/218000/instantclient-basic-linux.x64-21.8.0.0.0dbru.zip
apt install unzip
unzip instantclient-basic-linux.x64-21.8.0.0.0dbru.zip

wget https://download.oracle.com/otn_software/linux/instantclient/218000/instantclient-sqlplus-linux.x64-21.8.0.0.0dbru.zip
unzip instantclient-sqlplus-linux.x64-21.8.0.0.0dbru.zip

ls -la /opt/oracle/instantclient_21_8
sudo apt install libaio1
sudo sh -c "echo /opt/oracle/instantclient_21_8 > /etc/ld.so.conf.d/oracle-instantclient.conf"
sudo ldconfig
export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_8:$LD_LIBRARY_PATH
export PATH=/opt/oracle/instantclient_21_8:$PATH


#Connect to the oracle database

sqlplus 'admin@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=database-1.cnglh3wgxitt.eu-north-1.rds.amazonaws.com)(PORT=1521))(CONNECT_DATA=(SID=caching)))'


#Create the table in oracle

CREATE TABLE student (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nom VARCHAR2(50),
    prenom VARCHAR2(50),
    PRIMARY KEY (id)
);

#Insert data to student table

INSERT INTO student (nom, prenom)
VALUES ('Armand', 'karl');

INSERT INTO student (nom, prenom)
VALUES ('Frank', 'Ivan');


# install Python3

sudo apt update
sudo apt install python3 python3-pip -y


#additionnal configuration
python3 -m pip install --upgrade redis
pip install cx_Oracle

# try redis connection

import redis

client = redis.Redis(host='master.oracle-redis.agf95j.eun1.cache.amazonaws.com', port=6379)
response = client.ping()

if response:
    print("Connected to Redis server!")
else:
    print("Failed to connect to Redis server.")


4474 2000 6765 2102